apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "web-anuncios.fullname" . }}
  labels:
{{ include "web-anuncios.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "web-anuncios.name" . }}
      type: web
  template:
    metadata:
      labels:
{{ include "web-anuncios.labels" . | indent 8 }}
        type: web
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.webAnuncios.image.repository }}:{{ .Values.webAnuncios.image.tag }}"
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: {{ .Values.db.rootPassword }}
          - name: MYSQL_DATABASE
            value: {{ .Values.db.name }}
