apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "web-anuncios.fullname" . }}-db
  labels:
{{ include "web-anuncios.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "web-anuncios.name" . }}
      type: db
  template:
    metadata:
      labels:
{{ include "web-anuncios.labels" . | indent 8 }}
        type: db
    spec:
      containers:
        - name: {{ .Chart.Name }}-db
          image: "{{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}"
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: {{ .Values.db.rootPassword }}
          - name: MYSQL_DATABASE
            value: {{ .Values.db.name }}
          volumeMounts:
            - mountPath: "/var/lib/mysql"
              name: {{ .Values.db.volumeName }}
      volumes:
        - name: {{ .Values.db.volumeName }}
          persistentVolumeClaim:
            claimName: {{ include "web-anuncios.fullname" . }}-{{ .Values.db.pvc }}
