apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "web-anuncios.fullname" . }}-db
  labels:
    app.kubernetes.io/name: {{ include "web-anuncios.name" . }}
    type: db
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      type: db
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "web-anuncios.name" . }}
        type: db
    spec:
      containers:
        - name: {{ .Chart.Name }}-db
          image: mysql:5.6
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: {{ .Values.dbRootPassword }}
          - name: MYSQL_DATABASE
            value: {{ .Values.dbName }}
          volumeMounts:
            - mountPath: "/var/lib/mysql"
              name: webapp-db-storage
      volumes:
        - name: webapp-db-storage
          persistentVolumeClaim:
            claimName: webapp-pvc
