apiVersion: networking.k8s.io/v1beta1
kind: Ingress  
metadata:  
  name: {{ include "web-anuncios.fullname" . }}-ingress
  labels:
{{ include "web-anuncios.labels" . | indent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/$2"
spec:  
  rules:
  - host: {{ .Values.webAnuncios.ingress.host }}
    http:
      paths:
      - path: {{ .Values.webAnuncios.ingress.path }}(/|$)(.*)
        backend:
          serviceName: {{ include "web-anuncios.fullname" . }}-{{ .Values.webAnuncios.service.name }}
          servicePort: {{ .Values.webAnuncios.service.port }}