apiVersion: networking.k8s.io/v1beta1
kind: Ingress  
metadata:  
  name: {{ include "web-anuncios.fullname" . }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/$2"
spec:  
  rules:
  - host: www.webanuncios.com
    http:
      paths:
      - path: /anuncios(/|$)(.*)
        backend:
          serviceName: {{ include "web-anuncios.fullname" . }}
          servicePort: 8080