kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ include "web-anuncios.fullname" . }}-db-persistent-volume
  labels:
{{ include "web-anuncios.labels" . | indent 4 }}
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/{{ include "web-anuncios.fullname" . }}-data