kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "web-anuncios.fullname" . }}-{{ .Values.db.pvc }}
  labels:
{{ include "web-anuncios.labels" . | indent 4 }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi