apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.service.name }}
  labels:
{{ include "web-anuncios.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.db.service.port }}
      targetPort: {{ .Values.db.service.port }}
      protocol: TCP
      name: db
  selector:
    app.kubernetes.io/name: {{ include "web-anuncios.name" . }}
    type: db
