apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
{{ include "web-anuncios.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
      name: db
  selector:
    type: db
