apiVersion: v1
kind: Service
metadata:
  name: {{ include "web-anuncios.fullname" . }}
  labels:
{{ include "web-anuncios.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: web
  selector:
    app.kubernetes.io/name: {{ include "web-anuncios.name" . }}
