apiVersion: v1
kind: Service
metadata:
  name: {{ include "web-anuncios.fullname" . }}-service
  labels:
{{ include "web-anuncios.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.webAnuncios.service.port }}
      targetPort: {{ .Values.webAnuncios.service.port }}
      protocol: TCP
      name: {{ .Values.webAnuncios.service.name }}
  selector:
    app.kubernetes.io/name: {{ include "web-anuncios.name" . }}
