kind: PersistentVolume
apiVersion: v1
metadata:
  name: webapp-volume
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"